[unix_http_server]
file=/workspace/service-manager/run/supervisor.sock
chmod=0700

[supervisord]
nodaemon=true
logfile=/workspace/service-manager/log/supervisord.log
pidfile=/workspace/service-manager/run/supervisord.pid
childlogdir=/workspace/service-manager/log
loglevel=info
minfds=4096

[rpcinterface:supervisor]
supervisor.rpcinterface_factory=supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///workspace/service-manager/run/supervisor.sock

[include]
files=/workspace/shared-services/services/*.ini
